# Generated by Django 5.2.17 on 2026-09-22 11:19

import django.db.models.deletion
import django.utils.timezone
import lms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#10B981', max_length=7, verbose_name='Дополнительный цвет')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#111827', max_length=7, verbose_name='Цвет текста')),
                ('card_background', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Фон карточек')),
                ('navbar_background', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Фон навбара')),
                ('font_family', models.CharField(default='Inter, sans-serif', max_length=100, verbose_name='Шрифт')),
                ('border_radius', models.CharField(default='0.5rem', max_length=20, verbose_name='Скругление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('TEACHER', 'Преподаватель'), ('STUDENT', 'Ученик')], default='STUDENT', max_length=10, verbose_name='Роль')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', lms.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('subject', models.CharField(choices=[('MATH', 'Математика'), ('RUSSIAN', 'Русский язык'), ('PHYSICS', 'Физика'), ('CHEMISTRY', 'Химия'), ('BIOLOGY', 'Биология'), ('INFORMATICS', 'Информатика'), ('HISTORY', 'История'), ('SOCIAL', 'Обществознание'), ('ENGLISH', 'Английский язык'), ('GEOGRAPHY', 'География'), ('LITERATURE', 'Литература'), ('OTHER', 'Другое')], default='MATH', max_length=20, verbose_name='Предмет')),
                ('is_published', models.BooleanField(default=False, help_text='Показывать курс на главной странице (лендинге).', verbose_name='Опубликован')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.course', verbose_name='Курс')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='lms.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('order', 'id'),
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('task', models.TextField(verbose_name='Задание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='lms.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='lms.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ ученика')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('CHECKED', 'Проверено'), ('RETURNED', 'На доработку')], default='NEW', max_length=10, verbose_name='Статус')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.homework', verbose_name='Домашнее задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ответ на ДЗ',
                'verbose_name_plural': 'Ответы на ДЗ',
                'ordering': ('-submitted_at',),
                'unique_together': {('homework', 'student')},
            },
        ),
    ]
