# Generated by Django 5.2.17 on 2026-09-22 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'rtf', 'jpg', 'jpeg', 'png', 'webp', 'zip'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #RRGGBB.')], verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='border_radius',
            field=models.CharField(default='0.5rem', max_length=20, validators=[django.core.validators.RegexValidator('^(0|0?\\.[0-9]+|[1-9][0-9]*\\.?[0-9]*)(px|rem|em|%)$', 'Используйте значение с единицей px, rem, em или %.')], verbose_name='Скругление'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='card_background',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #RRGGBB.')], verbose_name='Фон карточек'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='navbar_background',
            field=models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #RRGGBB.')], verbose_name='Фон навбара'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(default='#4F46E5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #RRGGBB.')], verbose_name='Основной цвет'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(default='#10B981', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #RRGGBB.')], verbose_name='Дополнительный цвет'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_color',
            field=models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Укажите HEX-цвет в формате #RRGGBB.')], verbose_name='Цвет текста'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'created_at'], name='lms_course_is_publ_9f9360_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'created_at'], name='lms_course_teacher_337b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'student'], name='lms_enrollm_course__1955f3_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'created_at'], name='lms_homewor_course__c042f4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lms_lesson_course__d16254_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'status'], name='lms_submiss_student_dc5fc0_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['homework', 'status'], name='lms_submiss_homewor_365899_idx'),
        ),
    ]
