# Generated by Django 5.2.17 on 2026-09-22 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_customuser_avatar_alter_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font_family',
            field=models.CharField(default='Inter, sans-serif', max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-z0-9 ,\\'\\-]+$", 'Недопустимое значение шрифта.')], verbose_name='Шрифт'),
        ),
    ]
